//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R34Downloader.Resources {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("R34Downloader.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string SectionAuth { get { return ResourceManager.GetString("SectionAuth", resourceCulture); } }
        public static string SectionDownload { get { return ResourceManager.GetString("SectionDownload", resourceCulture); } }
        public static string SectionOptions { get { return ResourceManager.GetString("SectionOptions", resourceCulture); } }
        public static string SectionLog { get { return ResourceManager.GetString("SectionLog", resourceCulture); } }
        public static string LabelApiKey { get { return ResourceManager.GetString("LabelApiKey", resourceCulture); } }
        public static string LabelUserId { get { return ResourceManager.GetString("LabelUserId", resourceCulture); } }
        public static string LabelTagsFolder { get { return ResourceManager.GetString("LabelTagsFolder", resourceCulture); } }
        public static string LabelThreads { get { return ResourceManager.GetString("LabelThreads", resourceCulture); } }
        public static string ToolTipApiKey { get { return ResourceManager.GetString("ToolTipApiKey", resourceCulture); } }
        public static string PlaceholderUserId { get { return ResourceManager.GetString("PlaceholderUserId", resourceCulture); } }
        public static string PlaceholderDir { get { return ResourceManager.GetString("PlaceholderDir", resourceCulture); } }
        public static string CheckSkipExisting { get { return ResourceManager.GetString("CheckSkipExisting", resourceCulture); } }
        public static string CheckDryRun { get { return ResourceManager.GetString("CheckDryRun", resourceCulture); } }
        public static string BtnClearLog { get { return ResourceManager.GetString("BtnClearLog", resourceCulture); } }
        public static string BtnCheckAccess { get { return ResourceManager.GetString("BtnCheckAccess", resourceCulture); } }
        public static string BtnRebuildIndex { get { return ResourceManager.GetString("BtnRebuildIndex", resourceCulture); } }
        public static string BtnStop { get { return ResourceManager.GetString("BtnStop", resourceCulture); } }
        public static string BtnStart { get { return ResourceManager.GetString("BtnStart", resourceCulture); } }
        public static string StatusIdle { get { return ResourceManager.GetString("StatusIdle", resourceCulture); } }
        public static string BrowseFolderTitle { get { return ResourceManager.GetString("BrowseFolderTitle", resourceCulture); } }
        public static string ErrNoFolder { get { return ResourceManager.GetString("ErrNoFolder", resourceCulture); } }
        public static string ErrFolderNotFound { get { return ResourceManager.GetString("ErrFolderNotFound", resourceCulture); } }
        public static string ErrAlreadyRunning { get { return ResourceManager.GetString("ErrAlreadyRunning", resourceCulture); } }
        public static string StatusChecking { get { return ResourceManager.GetString("StatusChecking", resourceCulture); } }
        public static string StatusCheckDone { get { return ResourceManager.GetString("StatusCheckDone", resourceCulture); } }
        public static string StatusIndexing { get { return ResourceManager.GetString("StatusIndexing", resourceCulture); } }
        public static string StatusIndexDone { get { return ResourceManager.GetString("StatusIndexDone", resourceCulture); } }
        public static string StatusNoFolders { get { return ResourceManager.GetString("StatusNoFolders", resourceCulture); } }
        public static string StatusError { get { return ResourceManager.GetString("StatusError", resourceCulture); } }
        public static string StatusLoading { get { return ResourceManager.GetString("StatusLoading", resourceCulture); } }
        public static string StatusStopping { get { return ResourceManager.GetString("StatusStopping", resourceCulture); } }
        public static string LogStopSignal { get { return ResourceManager.GetString("LogStopSignal", resourceCulture); } }
        public static string LogNoFoldersInDir { get { return ResourceManager.GetString("LogNoFoldersInDir", resourceCulture); } }
        public static string LogRebuildHeader { get { return ResourceManager.GetString("LogRebuildHeader", resourceCulture); } }
        public static string LogRebuildDone { get { return ResourceManager.GetString("LogRebuildDone", resourceCulture); } }
        public static string LogStartHeader { get { return ResourceManager.GetString("LogStartHeader", resourceCulture); } }
        public static string LogDirLabel { get { return ResourceManager.GetString("LogDirLabel", resourceCulture); } }
        public static string LogThreadsLabel { get { return ResourceManager.GetString("LogThreadsLabel", resourceCulture); } }
        public static string LogDryRunLabel { get { return ResourceManager.GetString("LogDryRunLabel", resourceCulture); } }
        public static string LogSkipLabel { get { return ResourceManager.GetString("LogSkipLabel", resourceCulture); } }
        public static string LogAuthLabel { get { return ResourceManager.GetString("LogAuthLabel", resourceCulture); } }
        public static string LogAuthAnon { get { return ResourceManager.GetString("LogAuthAnon", resourceCulture); } }
        public static string LogNoFolders { get { return ResourceManager.GetString("LogNoFolders", resourceCulture); } }
        public static string LogArtistCount { get { return ResourceManager.GetString("LogArtistCount", resourceCulture); } }
        public static string LogCollecting { get { return ResourceManager.GetString("LogCollecting", resourceCulture); } }
        public static string StatusCollecting { get { return ResourceManager.GetString("StatusCollecting", resourceCulture); } }
        public static string LogNoPostsFound { get { return ResourceManager.GetString("LogNoPostsFound", resourceCulture); } }
        public static string LogFolderProgress { get { return ResourceManager.GetString("LogFolderProgress", resourceCulture); } }
        public static string LogPostsFound { get { return ResourceManager.GetString("LogPostsFound", resourceCulture); } }
        public static string LogDryRunSkip { get { return ResourceManager.GetString("LogDryRunSkip", resourceCulture); } }
        public static string StatusDownloading { get { return ResourceManager.GetString("StatusDownloading", resourceCulture); } }
        public static string LogFolderDone { get { return ResourceManager.GetString("LogFolderDone", resourceCulture); } }
        public static string LogStoppedByUser { get { return ResourceManager.GetString("LogStoppedByUser", resourceCulture); } }
        public static string StatusStopped { get { return ResourceManager.GetString("StatusStopped", resourceCulture); } }
        public static string LogFinished { get { return ResourceManager.GetString("LogFinished", resourceCulture); } }
        public static string StatusFinished { get { return ResourceManager.GetString("StatusFinished", resourceCulture); } }
        public static string LogTotalTime { get { return ResourceManager.GetString("LogTotalTime", resourceCulture); } }
        public static string LogCheckAccessHeader { get { return ResourceManager.GetString("LogCheckAccessHeader", resourceCulture); } }
        public static string LogSiteName { get { return ResourceManager.GetString("LogSiteName", resourceCulture); } }
        public static string LogApiName { get { return ResourceManager.GetString("LogApiName", resourceCulture); } }
        public static string LogApiKeyCheck { get { return ResourceManager.GetString("LogApiKeyCheck", resourceCulture); } }
        public static string LogApiKeyOk { get { return ResourceManager.GetString("LogApiKeyOk", resourceCulture); } }
        public static string LogApiKeyFail { get { return ResourceManager.GetString("LogApiKeyFail", resourceCulture); } }
        public static string LogApiKeyUnknown { get { return ResourceManager.GetString("LogApiKeyUnknown", resourceCulture); } }
        public static string LogNoAuth { get { return ResourceManager.GetString("LogNoAuth", resourceCulture); } }
        public static string LogSeparator { get { return ResourceManager.GetString("LogSeparator", resourceCulture); } }
        public static string LogFilesInIndex { get { return ResourceManager.GetString("LogFilesInIndex", resourceCulture); } }
        public static string LogFoldersProgress { get { return ResourceManager.GetString("LogFoldersProgress", resourceCulture); } }
        public static string LogErrorPrefix { get { return ResourceManager.GetString("LogErrorPrefix", resourceCulture); } }
        public static string LogUnexpectedError { get { return ResourceManager.GetString("LogUnexpectedError", resourceCulture); } }
    }
}
